# Generated by Django 3.2.12 on 2022-03-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('collected', models.IntegerField(default=0)),
                ('missing', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected', models.BooleanField(default=False)),
                ('cardid', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('defence', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('attribute', models.CharField(blank=True, max_length=100)),
                ('cardsetname', models.TextField(blank=True)),
                ('cardsetcode', models.CharField(blank=True, max_length=100)),
                ('cardsetrarity', models.CharField(blank=True, max_length=100)),
                ('cardsetraritycode', models.CharField(blank=True, max_length=100)),
                ('image_url', models.TextField(blank=True)),
                ('image_url_small', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='')),
                ('image_small', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='')),
                ('userset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userset')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
